language: php

php: 
  - 5.4

before_script:
  - mysql -e 'CREATE DATABASE ˋlarafolio-testingˋ;'
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: phpunit